### ISSUE TITLE
ModuleNotFoundError: No module named 'pie.models.loaders'

### ISSUE THREAD

**Issue by OrianeN** [lascivaroma/PaPie#8]
In a common project with @PonteIneptique, I would like to train some PaPie models, yet I'm facing an error when running the training command.

Here are the steps I did:
- clone PaPie repo
- create new conda env with python3.11
- install the repo with `pip install .`
- run `pip eval --help`  to check installation
- run `pie train my_config.json` to launch training -> got "ModuleNotFoundError: No module named 'pie.models.loaders'"
- set PYTHONPATH to the PaPie folder -> same error

Here's the detail of the error:
```
Traceback (most recent call last):
  File "/.../AnaConda/miniconda3/envs/papie-py311/bin/pie", line 8, in <module>
    sys.exit(pie_cli())
             ^^^^^^^^^
  File "/.../AnaConda/miniconda3/envs/papie-py311/lib/python3.11/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../AnaConda/miniconda3/envs/papie-py311/lib/python3.11/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.../AnaConda/miniconda3/envs/papie-py311/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../AnaConda/miniconda3/envs/papie-py311/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../AnaConda/miniconda3/envs/papie-py311/lib/python3.11/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../scratch/tagging/occitan/papie/PaPie/pie/scripts/group.py", line 106, in train
    import pie.scripts.train
  File "/.../scratch/tagging/occitan/papie/PaPie/pie/scripts/train.py", line 13, in <module>
    from pie.models import SimpleModel
  File "/.../scratch/tagging/occitan/papie/PaPie/pie/models/__init__.py", line 8, in <module>
    from .loaders import get_pretrained_embeddings
ModuleNotFoundError: No module named 'pie.models.loaders'
```

Note that my script was running the `pie eval ...` command right after and I got the same error with it (but I didn't get any error with the `--help` option)

When looking inside the `pie.models` folder of the repo, I can't find the `loaders.py` module - should I get it from somewhere else ?

**Comment by OrianeN** [comment]
Fixed with commit https://github.com/lascivaroma/PaPie/commit/85fcc90400721e7d03fa7a3a33dabee2001e4126 : thanks @PonteIneptique !

**Comment by OrianeN** [comment]
Fixed with commit https://github.com/lascivaroma/PaPie/commit/85fcc90400721e7d03fa7a3a33dabee2001e4126: thanks @PonteIneptique !
